Plat 787 gruf rollbar reporting
sealink/gruf-rollbar pull request #2
Opened 2022-10-04 06:03 UTC by jiaoshen110

**WHY**

Integration with rollbar

**Test**

Install this project locally and follow the readme to set up it

2022-10-04 22:32 UTC, jmortlock approved these changes

2022-10-04 22:33 UTC, Damon1024 approved these changes

2022-10-04 22:34 UTC, jmortlock requested changes
Requires a ChangeLog you should also add the standard .gitattributes file we use to handle merge conflicts in it

2022-10-04 22:35 UTC, jmortlock commented on gruf-rollbar.gemspec
> +  spec.authors       = ['Sealink']
Should be SeaLink

2022-10-04 23:11 UTC, jiaoshen110 commented on gruf-rollbar.gemspec
> +  spec.authors       = ['Sealink']
yep, updated

2022-10-04 23:27 UTC, Damon1024 approved these changes

2022-10-05 01:11 UTC, jmortlock approved these changes

2022-10-05 01:12 UTC, merged